"""vit

Revision ID: 281ad827a3eb
Revises: f891e4d04374
Create Date: 2024-09-29 01:54:25.088495

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '281ad827a3eb'
down_revision = 'f891e4d04374'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('video', sa.Column('model_3_e', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('video', 'model_3_e')
    # ### end Alembic commands ###
